[project]
name = "boredapi-explore"
version = "0.1.0"
description = "boredapi exploration"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "polars>=1.32.3",
    "requests>=2.32.5",
]
